apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-bmangesh-pvc
  namespace: bmangesh
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
