apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-codeserver-bmangesh-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/bmangesh"
