---
kind: ConfigMap
apiVersion: v1
metadata:
  name: octavia-ingress-controller-config
  namespace: kube-system
data:
  config: |
    cluster-name: cisco
    openstack:
      auth-url: https://cloud-svlstg-1.cisco.com:5000/v3
      domain-name: cisco
      username: mabharsa
      # user-id: ${user_id}
      password: ${password}
      project-id: ${projectID}
      region: cloud-svlstg-1
    octavia:
      subnet-id: ${subnetID}
