apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-ui-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/cloud"
