apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nextcloud-mysql-pvc
   namespace: nextcloud
   labels:
      app: nextcloud
spec:
   storageClassName: manual
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
