apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: white-board-pvc
  namespace: white-board
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi